version: '3.8'  # Versi칩n de Docker Compose que se utilizar치

services:  # Define los servicios de contenedores que se ejecutar치n

  db-mongo:  # Nombre del servicio (puede ser cualquier nombre que desees)
    container_name: mongo_db_Hero
    image: mongo  # Imagen de Docker que se utilizar치 para este servicio
    ports: 
    - "27017:27017"

  web-app:  # Otro servicio llamado "web"
    image: node:18.20.1-alpine
    container_name: NodeHeroApi
    build: ./API  # Directorio que contiene el Dockerfile para construir la imagen
    ports:  # Mapeo de puertos entre el host y el contenedor
      - "5000:5000"  # Mapeo del puerto 8000 del host al puerto 8000 del contenedor
    volumes:  # Volumen para montar un directorio del host dentro del contenedor
      - ./API:/API  # Montar el directorio "app" del host en "/code" dentro del contenedor
    command: sh -c "node index.js"
    depends_on:  # Dependencias del servicio web
      - db-mongo # Indicar que este servicio depende del servicio "db"
